// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Main from "./Main.bs.js";
import * as React from "react";
import * as Client from "react-dom/client";

var root = document.querySelector("#root");

if (!(root == null)) {
  Client.createRoot(root).render(React.createElement(Main.make, {}));
}

export {
  
}
/* root Not a pure module */
