// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ConnectWalletButton(Props) {
  return React.createElement("div", {
              className: "flex items-center gap-x-1 cursor-pointer",
              onClick: (function (param) {
                  console.log("connect wallet button clicked");
                  
                })
            }, React.createElement("span", undefined, "Connect Wallet"));
}

var make = ConnectWalletButton;

export {
  make ,
  
}
/* react Not a pure module */
