// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ConnectWalletButton(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("button", {
              className: "flex items-center gap-x-1 cursor-pointer " + className,
              type: "button",
              onClick: (function (param) {
                  console.log("connect wallet button clicked");
                  
                })
            }, React.createElement("span", undefined, "Connect Wallet"));
}

var make = ConnectWalletButton;

export {
  make ,
  
}
/* react Not a pure module */
