// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function EthCurrencyImage(Props) {
  return React.createElement("img", {
              alt: "eth logo",
              height: "20",
              src: "../assets/ethCurrency.png",
              width: "20"
            });
}

var make = EthCurrencyImage;

export {
  make ,
  
}
/* react Not a pure module */
