// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function EthImage(Props) {
  var classNameOpt = Props.className;
  var heightOpt = Props.height;
  var widthOpt = Props.width;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var height = heightOpt !== undefined ? heightOpt : "20";
  var width = widthOpt !== undefined ? widthOpt : "20";
  return React.createElement("img", {
              className: className,
              alt: "eth logo",
              height: height,
              src: "../assets/eth.png",
              width: width
            });
}

var make = EthImage;

export {
  make ,
  
}
/* react Not a pure module */
