// Generated by ReScript, PLEASE EDIT WITH CARE


function make(number, prime) {
  if (number >= prime || number < 0) {
    return {
            TAG: /* Error */1,
            _0: "Number " + String(number) + " is not in field range 0 to " + String(prime)
          };
  } else {
    return {
            TAG: /* Ok */0,
            _0: {
              number: number,
              prime: prime
            }
          };
  }
}

export {
  make ,
  
}
/* No side effect */
