// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Header(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", {
                  className: "text-xl"
                }, "Header"));
}

var make = Header;

export {
  make ,
  
}
/* react Not a pure module */
