// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as EthImage from "./EthImage.bs.js";
import * as Ai from "react-icons/ai";
import * as HiOutlineDotsVertical from "./HiOutlineDotsVertical.bs.js";

function HeaderButtons(Props) {
  return React.createElement("div", {
              className: "flex gap-x-4 items-center"
            }, React.createElement("div", {
                  className: "flex items-center gap-x-1 cursor-pointer",
                  onClick: (function (param) {
                      console.log("eth button clicked");
                      
                    })
                }, React.createElement(EthImage.make, {}), React.createElement("span", undefined, "Ethereum"), React.createElement(Ai.AiOutlineDown, {})), React.createElement(HiOutlineDotsVertical.make, {
                  onClick: (function (param) {
                      console.log("clicked dots");
                      
                    })
                }));
}

var make = HeaderButtons;

export {
  make ,
  
}
/* react Not a pure module */
