// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nav from "./Nav.bs.js";
import * as React from "react";
import * as UniswapImage from "./UniswapImage.bs.js";
import * as HeaderButtons from "./HeaderButtons.bs.js";

function Header(Props) {
  React.useEffect((function () {
          console.log("effect 0");
          
        }), []);
  return React.createElement("div", {
              className: "flex justify-between items-center"
            }, React.createElement(UniswapImage.make, {}), React.createElement(Nav.make, {}), React.createElement(HeaderButtons.make, {}));
}

var make = Header;

export {
  make ,
  
}
/* Nav Not a pure module */
