// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Hi from "react-icons/hi";

var Icon = {};

function HiOutlineDotsVertical(Props) {
  var onClick = Props.onClick;
  return React.createElement("div", {
              className: "cursor-pointer",
              onClick: onClick
            }, React.createElement(Hi.HiOutlineDotsVertical, {}));
}

var make = HiOutlineDotsVertical;

export {
  Icon ,
  make ,
  
}
/* react Not a pure module */
