// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Main(Props) {
  return React.createElement("div", {
              className: "px-2 flex items-center justify-between font-semibold text-xl"
            }, React.createElement("span", undefined, "Swap"));
}

var make = Main;

export {
  make ,
  
}
/* react Not a pure module */
