// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header from "./Header.bs.js";

function Main(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "flex flex-col justify-between bg-gray-100 w-screen h-screen max-h-screen min-h-screen"
                }, React.createElement(Header.make, {}), React.createElement("h1", {
                      className: "text-xl"
                    }, "Bye")));
}

var make = Main;

export {
  make ,
  
}
/* react Not a pure module */
