// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Main(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("a", {
                  className: "text-red-400 text-4xl bg-blue-50 block text-center p-2 hover:text-blue-800",
                  href: "https://www.youtube.com/watch?v=xXxjRzdYIss",
                  rel: "noopener noreferrer",
                  target: "_blank"
                }, "Uniswap Tutorial"));
}

var make = Main;

export {
  make ,
  
}
/* react Not a pure module */
