// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function NavItem(Props) {
  var onClick = Props.onClick;
  var children = Props.children;
  return React.createElement("span", {
              className: "cursor-pointer font-medium rounded-3xl",
              onClick: onClick
            }, children);
}

var make = NavItem;

export {
  make ,
  
}
/* react Not a pure module */
