// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Restorative from "./Restorative.bs.js";

var initialState = {
  selectedNav: /* Swap */0
};

function reducer(state, action) {
  return {
          selectedNav: action._0
        };
}

var match = Restorative.createStore(initialState, reducer);

var dispatch = match.dispatch;

var useStore = match.useStore;

export {
  initialState ,
  reducer ,
  dispatch ,
  useStore ,
  
}
/* match Not a pure module */
