// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Main from "./Main.bs.js";
import * as React from "react";
import * as Header from "./Header.bs.js";

function Uniswap(Props) {
  return React.createElement("div", {
              className: "flex flex-col justify-between bg-violet-900 w-screen h-screen max-h-screen min-h-screen"
            }, React.createElement(Header.make, {}), React.createElement(Main.make, {}));
}

var make = Uniswap;

export {
  make ,
  
}
/* Main Not a pure module */
