// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function UniswapImage(Props) {
  return React.createElement("img", {
              alt: "uniswap",
              height: "20",
              src: "../assets/uniswap.png",
              width: "20"
            });
}

var make = UniswapImage;

export {
  make ,
  
}
/* react Not a pure module */
